version: "3"
services:
  web:
    build: dev.Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
      PORT: 8080
  db:
    image: mongo:3